apiVersion: apps/v1
kind: Deployment
metadata:
  name: iot-hub-hono
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iot-hub-hono
  template:
    metadata:
      labels:
        app: iot-hub-hono
    spec:
      containers:
      - name: hono
        image: eclipse/mosquitto:latest  # Alternative image (e.g., MQTT broker)
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8083
