apiVersion: v1
kind: Service
metadata:
  name: iot-hub-hono
  namespace: default
spec:
  selector:
    app: iot-hub-hono
  ports:
    - protocol: TCP
      port: 8083         # Port on which the service is exposed
      targetPort: 8083    # Port on the container to forward traffic to
  type: ClusterIP  # Exposes the service within the cluster; use LoadBalancer or NodePort for external access
