apiVersion: apps/v1
kind: Deployment
metadata:
  name: superset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superset
  template:
    metadata:
      labels:
        app: superset
    spec:
      containers:
      - name: superset
        image: apache/superset:latest
        resources:
          requests:
            memory: "64Mi"  # Minimum amount of memory requested
            cpu: "250m"     # Minimum amount of CPU requested
          limits:
            memory: "128Mi"  # Maximum amount of memory allowed
            cpu: "500m"      # Maximum amount of CPU allowed
        env:
        - name: SUPERSET_HOME
          value: "/usr/local/lib/python3.8/site-packages/superset"
        ports:
        - containerPort: 8088
