apiVersion: v1
kind: Pod
metadata:
  name: consumer-pod
spec:
  containers:
    - name: consumer-container
      image: guri-sekhon/consumer-image:latest
      resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
